// <auto-generated />
using System;
using HojeNoRU_API.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HojeNoRU_API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251015233640_AjusteParse")]
    partial class AjusteParse
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.10");

            modelBuilder.Entity("HojeNoRU_API.Models.ItemCardapio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("RefeicaoId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("RefeicaoId");

                    b.ToTable("ItensCardapio");
                });

            modelBuilder.Entity("HojeNoRU_API.Models.RU", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("RUs");
                });

            modelBuilder.Entity("HojeNoRU_API.Models.Refeicao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly>("Data")
                        .HasColumnType("TEXT");

                    b.Property<string>("DiaSemana")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("RUId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Tipo")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("RUId");

                    b.ToTable("Refeicoes");
                });

            modelBuilder.Entity("HojeNoRU_API.Models.ItemCardapio", b =>
                {
                    b.HasOne("HojeNoRU_API.Models.Refeicao", "Refeicao")
                        .WithMany("Itens")
                        .HasForeignKey("RefeicaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Refeicao");
                });

            modelBuilder.Entity("HojeNoRU_API.Models.Refeicao", b =>
                {
                    b.HasOne("HojeNoRU_API.Models.RU", "RU")
                        .WithMany("Refeicoes")
                        .HasForeignKey("RUId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RU");
                });

            modelBuilder.Entity("HojeNoRU_API.Models.RU", b =>
                {
                    b.Navigation("Refeicoes");
                });

            modelBuilder.Entity("HojeNoRU_API.Models.Refeicao", b =>
                {
                    b.Navigation("Itens");
                });
#pragma warning restore 612, 618
        }
    }
}
